[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "python-project01"
version = "0.1.0"
dependencies = [
    "python>=3.8",
]

[tool.black]
line-length = 88
target-version = ['py38']

[tool.isort]
profile = "black"
